spring.application.name=connectmeet-app

# H2 Database - local development
spring.datasource.url=jdbc:h2:mem:connectmeet
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Disable Open Session in View
spring.jpa.open-in-view=false

# Server
server.port=8081